### ISSUE TITLE
Extract event data from process execution from Bonitastudio

### ISSUE THREAD

**Issue by christbryan** [Bonitasoft-Community/bonita-server-logs#2]
Hello

I am working on a project and constructed my Bonita solution and executed it over a hundred of time. I would like to carry the project to the process mining phase and for me to carry out process mining I must have 3 fundamentals information: ID of the activities found in my process, the name of the activities and the timestamp of when the activities have been done.

I now need to extract the information from Bonitastudio but don't know how to extract these information. I had a look from the app website but could not find something that fulfilled my need.

I will be glad if you could give a help that could guide me please.

Thanks!

**Comment by rbioteau** [comment]
I've tried to give you hints on the [community forum](https://community.bonitasoft.com/answer-data-science-and-bpm-0#comment-14111)
